# Generated by Django 4.2.30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0003_studentguardianrelation_current_primary'),
        ('academics', '0004_academic_cycle_foundation'),
        ('attendance', '0004_alter_attendancealert_alert_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceThresholdParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_absences', models.PositiveIntegerField()),
                ('lookback_days', models.PositiveIntegerField()),
                ('effective_from', models.DateField()),
                ('academic_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absence_threshold_parameters', to='academics.academiccycle')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absence_threshold_parameters', to='academics.shift')),
            ],
            options={
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['shift', 'academic_cycle', 'effective_from'], name='reporting_threshold_lookup_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='absencethresholdparameters',
            constraint=models.UniqueConstraint(fields=('shift', 'academic_cycle', 'effective_from'), name='unique_absence_threshold_parameters_effective_from'),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('alert_type', models.CharField(choices=[('ausente_sin_registro', 'Ausencia no registrada'), ('permanencia_sin_cierre', 'Permanencia sin cierre'), ('frecuencia_ausencias', 'Ausencias frecuentes'), ('inconsistencia', 'Inconsistencia entre fuentes')], max_length=30)),
                ('event_date', models.DateField()),
                ('target_roles', models.JSONField(default=list)),
                ('context', models.JSONField(default=dict)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_reporting_alerts', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reporting_alerts', to='academics.section')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reporting_alerts', to='academics.shift')),
                ('source_attendance_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reporting_alerts', to='attendance.attendancealert')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reporting_alerts', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'shift', 'event_date', 'alert_type'], name='reporting_alert_lookup_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student', 'shift', 'event_date', 'alert_type'), name='unique_active_alert_per_student_day_type')],
            },
        ),
    ]
