# Generated by Django 4.2.30 on 2026-08-11 01:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_teaching_assignment_periods'),
    ]

    operations = [
        migrations.CreateModel(
            name='JornadaParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('entry_limit_time', models.TimeField()),
                ('tolerance_minutes', models.PositiveIntegerField()),
                ('closing_time', models.TimeField()),
                ('duplicate_suppression_minutes', models.PositiveIntegerField()),
                ('school_days', models.JSONField(default=list)),
                ('effective_from', models.DateField()),
                ('academic_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jornada_parameters', to='academics.academiccycle')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jornada_parameters', to='academics.shift')),
            ],
            options={
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['shift', 'academic_cycle', 'effective_from'], name='attendance_params_lookup_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='jornadaparameters',
            constraint=models.UniqueConstraint(fields=('shift', 'academic_cycle', 'effective_from'), name='unique_jornada_parameters_effective_from'),
        ),
    ]
