# Generated by Django 4.2.30 on 2026-08-11 03:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentguardianrelation_current_primary'),
        ('academics', '0003_teaching_assignment_periods'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event_date', models.DateField()),
                ('movement_type', models.CharField(choices=[('entry', 'Ingreso'), ('exit', 'Egreso')], max_length=10)),
                ('origin', models.CharField(choices=[('scan', 'Escaneo'), ('manual', 'Manual'), ('declared', 'Declarado')], max_length=10)),
                ('transmission', models.CharField(choices=[('individual', 'Individual'), ('batch', 'Lote')], default='individual', max_length=12)),
                ('captured_at', models.DateTimeField()),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_events', to='academics.shift')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_events', to='students.student')),
            ],
            options={
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['student', 'shift', 'event_date', 'movement_type'], name='attendance_event_prec_idx')],
            },
        ),
    ]
