# Generated by Django 4.2.30 on 2026-08-12 18:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentguardianrelation_current_primary'),
        ('academics', '0003_teaching_assignment_periods'),
        ('attendance', '0002_attendanceevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('alert_type', models.CharField(choices=[('permanencia_sin_cierre', 'Permanencia sin cierre')], max_length=30)),
                ('event_date', models.DateField()),
                ('target_roles', models.JSONField(default=list)),
                ('context', models.JSONField(default=dict)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_alerts', to='academics.section')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_alerts', to='academics.shift')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_alerts', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'shift', 'event_date', 'alert_type'], name='attendance_alert_lookup_idx')],
            },
        ),
    ]
