# Generated by Django 4.2.30 on 2026-08-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancealert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancealert',
            name='alert_type',
            field=models.CharField(choices=[('permanencia_sin_cierre', 'Permanencia sin cierre'), ('inconsistencia', 'Inconsistencia entre fuentes')], max_length=30),
        ),
    ]
