# Generated by Django 5.2.16 on 2026-08-19 07:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_academic_cycle_foundation'),
        ('attendance', '0004_alter_attendancealert_alert_type'),
        ('students', '0005_merge_student_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceevent',
            name='batch_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='attendanceevent',
            name='client_event_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='attendanceevent',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_events_operated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ControlPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='control_points', to='academics.campus')),
            ],
        ),
        migrations.AddField(
            model_name='attendanceevent',
            name='control_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_events', to='attendance.controlpoint'),
        ),
        migrations.AddConstraint(
            model_name='attendanceevent',
            constraint=models.UniqueConstraint(condition=models.Q(('client_event_id', ''), _negated=True), fields=('client_event_id',), name='unique_attendance_event_client_event_id'),
        ),
        migrations.AddConstraint(
            model_name='controlpoint',
            constraint=models.UniqueConstraint(fields=('campus', 'code'), name='unique_control_point_code_per_campus'),
        ),
    ]
