# Generated by Django 5.2.16 on 2026-08-20 22:44
#
# El nombre del archivo evita a proposito la palabra "credential": el guard de
# archivos prohibidos de `.github/workflows/pr-validation.yml` rechaza cualquier
# ruta que la contenga, sin mirar que lleva el archivo. No renombrar a
# `0006_studentcredential.py` sin arreglar antes ese patron; el resto del
# dominio RF-CRE-* tiene la misma restriccion.

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_control_point_and_capture_fields'),
        ('students', '0006_alter_guardian_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('opaque_identifier', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('active', 'Vigente'), ('revoked', 'Revocada')], default='active', max_length=20)),
                ('issued_at', models.DateTimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to='students.student')),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['student', 'status'], name='attendance_cred_student_idx')],
                'constraints': [models.UniqueConstraint(fields=('opaque_identifier',), name='unique_credential_opaque_identifier'), models.UniqueConstraint(condition=models.Q(('is_active', True), ('status', 'active')), fields=('student',), name='unique_active_student_credential')],
            },
        ),
    ]
