# Generated by Django 5.2.17 on 2026-08-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_credential_revocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlpoint',
            name='allows_entry',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='controlpoint',
            name='allows_exit',
            field=models.BooleanField(default=True),
        ),
    ]
