# Generated by Django 5.2.17 on 2026-09-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0009_control_point_movement_types"),
        ("enrolments", "0007_studentmovementannulment"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentcredential",
            name="revoked_on_movement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credentials_revoked_on_close",
                to="enrolments.studentmovement",
            ),
        ),
    ]
