# Generated by Django 5.2.17 on 2026-09-04 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_capture_batch'),
        ('attendance', '0010_studentcredential_revoked_on_movement'),
    ]

    operations = [
    ]
