# Generated by Django 5.2.17 on 2026-09-02 05:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_classschedulepublication'),
        ('attendance', '0010_capture_batch'),
        ('attendance', '0010_studentcredential_revoked_on_movement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionClosureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event_date', models.DateField()),
                ('is_covering', models.BooleanField()),
                ('included_count', models.PositiveIntegerField()),
                ('omitted_count', models.PositiveIntegerField()),
                ('declared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_closures_declared', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closure_logs', to='academics.section')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
