# Generated by Django 5.2 on 2026-09-05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0011_merge_20260902_1743"),
        ("attendance", "0011_merge_20260904_1340"),
        ("attendance", "0011_section_closure_log"),
    ]

    operations = []
