# Generated by Django 5.2.17 on 2026-09-11 13:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_justification_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='JustificationReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='justification',
            name='situation_type',
            field=models.CharField(choices=[('absence', 'Inasistencia'), ('late_arrival', 'Llegada tardia')], default='absence', max_length=15),
        ),
        migrations.AddField(
            model_name='justification',
            name='reason_catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='justifications', to='attendance.justificationreason'),
        ),
    ]
