# Generated by Django 4.2.30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee_code', models.CharField(max_length=50, unique=True)),
                ('specialty', models.CharField(max_length=150)),
                ('position', models.CharField(choices=[('Docente Titulado', 'Docente Titulado'), ('Docente Interino', 'Docente Interino'), ('Orientador/a', 'Orientador/a'), ('Administrativo', 'Administrativo')], max_length=20)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('photo', models.FileField(blank=True, upload_to='teacher_photos/')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_profile', to='people.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
