# Generated by Django 5.2.16 on 2026-08-19 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['employee_code']},
        ),
    ]
