version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "area:frontend"
    groups:
      frontend-dev-patch-minor:
        dependency-type: "development"
        update-types:
          - "patch"
          - "minor"
      frontend-prod-patch:
        dependency-type: "production"
        update-types:
          - "patch"

  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "area:backend"
    groups:
      backend-dev-patch-minor:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "area:devops"
    groups:
      github-actions-compatible:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "area:docker"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "area:docker"
