# Generated by Django 5.2.17 on 2026-09-17 16:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(db_index=True, help_text='Identificador estable de la tarea, normalmente el comando que la ejecuta.', max_length=100)),
                ('status', models.CharField(choices=[('running', 'En ejecucion'), ('succeeded', 'Finalizada'), ('failed', 'Fallida')], default='running', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('host', models.CharField(blank=True, default='', max_length=255)),
                ('process_id', models.PositiveIntegerField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error_type', models.CharField(blank=True, default='', max_length=150)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['name', '-started_at'], name='task_run_name_recent_idx')],
            },
        ),
    ]
