from django.urls import path

from apps.attendance.api.views import (
    AttendanceAlertListView,
    AttendanceDayStatusView,
    AttendanceEventListCreateView,
    AttendanceEventResolutionView,
    AttendancePercentageView,
    AttendancePresenceListView,
    AttendanceScanView,
    CaptureBatchConfirmView,
    CaptureBatchCurrentView,
    CaptureBatchOpenView,
    ControlPointListView,
    CredentialPrintContentView,
    CredentialRevocationView,
    JornadaClosureView,
    JornadaParametersListCreateView,
    ManualRegistrationReasonListView,
    SectionClosurePreviewView,
    SectionClosureView,
    StudentCredentialIssueView,
    StudentCredentialResolutionView,
)

urlpatterns = [
    path(
        "jornada-parameters/",
        JornadaParametersListCreateView.as_view(),
        name="attendance-jornada-parameters-list",
    ),
    path(
        "events/",
        AttendanceEventListCreateView.as_view(),
        name="attendance-event-list",
    ),
    path(
        "events/resolution/",
        AttendanceEventResolutionView.as_view(),
        name="attendance-event-resolution",
    ),
    path(
        "day-status/",
        AttendanceDayStatusView.as_view(),
        name="attendance-day-status",
    ),
    path(
        "jornada-closures/",
        JornadaClosureView.as_view(),
        name="attendance-jornada-closures",
    ),
    path(
        "section-closures/",
        SectionClosureView.as_view(),
        name="attendance-section-closure",
    ),
    path(
        "section-closures/preview/",
        SectionClosurePreviewView.as_view(),
        name="attendance-section-closure-preview",
    ),
    path(
        "alerts/",
        AttendanceAlertListView.as_view(),
        name="attendance-alert-list",
    ),
    path(
        "presence/",
        AttendancePresenceListView.as_view(),
        name="attendance-presence",
    ),
    path(
        "attendance-percentage/",
        AttendancePercentageView.as_view(),
        name="attendance-percentage",
    ),
    path(
        "control-points/",
        ControlPointListView.as_view(),
        name="attendance-control-point-list",
    ),
    path(
        "scan/",
        AttendanceScanView.as_view(),
        name="attendance-scan",
    ),
    path(
        "capture-batches/",
        CaptureBatchOpenView.as_view(),
        name="attendance-capture-batch-open",
    ),
    path(
        "capture-batches/current/",
        CaptureBatchCurrentView.as_view(),
        name="attendance-capture-batch-current",
    ),
    path(
        "capture-batches/<uuid:public_id>/confirm/",
        CaptureBatchConfirmView.as_view(),
        name="attendance-capture-batch-confirm",
    ),
    path(
        "manual-registration-reasons/",
        ManualRegistrationReasonListView.as_view(),
        name="attendance-manual-registration-reason-list",
    ),
    path(
        "credentials/",
        StudentCredentialIssueView.as_view(),
        name="attendance-credential-issue",
    ),
    path(
        "credentials/print-content/",
        CredentialPrintContentView.as_view(),
        name="attendance-credential-print-content",
    ),
    path(
        "credentials/revoke/",
        CredentialRevocationView.as_view(),
        name="attendance-credential-revoke",
    ),
    path(
        "credentials/resolve/",
        StudentCredentialResolutionView.as_view(),
        name="attendance-credential-resolve",
    ),
]
