# Generated by Django 4.2.30 on 2026-08-03 22:56
# Hand-reordered: the autodetector grouped every AddConstraint for a model
# right after its "simple" field changes, ahead of the AddField operations
# for FK columns that needed a one-off default (level, offering, campus).
# Those constraints reference fields that did not exist yet at that point in
# the operation list, so this file reorders operations to satisfy every field
# dependency before the constraint that references it.

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('is_main', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'campuses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GradeOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['shift__campus__name', 'grade__level__sequence', 'grade__sequence'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30)),
                ('sequence', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['sequence', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LevelSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=True)),
                ('weekly_hours', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['level__sequence', 'subject__name'],
            },
        ),
        migrations.AddField(
            model_name='campus',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='academics.institution'),
        ),
        migrations.AddField(
            model_name='level',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='academics.institution'),
        ),
        migrations.AddField(
            model_name='levelsubject',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_subjects', to='academics.level'),
        ),
        migrations.AddField(
            model_name='levelsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_subjects', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='gradeoffering',
            name='academic_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_offerings', to='academics.academiccycle'),
        ),
        migrations.AddField(
            model_name='gradeoffering',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='academics.grade'),
        ),
        migrations.AddField(
            model_name='gradeoffering',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_offerings', to='academics.shift'),
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['level__sequence', 'sequence', 'name']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['offering__grade__level__sequence', 'offering__grade__sequence', 'name']},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['campus__name', 'name']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='shift',
            name='institution',
        ),
        migrations.AddField(
            model_name='shift',
            name='campus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='academics.campus'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='section',
            name='academic_cycle',
        ),
        migrations.RemoveField(
            model_name='section',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='section',
            name='shift',
        ),
        migrations.AddField(
            model_name='section',
            name='offering',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.gradeoffering'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='sequence',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='institution',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academics.institution'),
        ),
        migrations.AddField(
            model_name='grade',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='academics.level'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='levels',
            field=models.ManyToManyField(blank=True, related_name='subjects', through='academics.LevelSubject', to='academics.level'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('level', 'sequence'), name='unique_grade_sequence_per_level'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='unique_grade_code_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('offering', 'name'), name='unique_section_name_per_offering'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('campus', 'code'), name='unique_shift_code_per_campus'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='unique_subject_code_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='levelsubject',
            constraint=models.UniqueConstraint(fields=('level', 'subject'), name='unique_subject_per_level'),
        ),
        migrations.AddConstraint(
            model_name='level',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='unique_level_code_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='level',
            constraint=models.UniqueConstraint(fields=('institution', 'sequence'), name='unique_level_sequence_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='level',
            constraint=models.UniqueConstraint(fields=('id', 'institution'), name='unique_level_id_institution'),
        ),
        migrations.AddConstraint(
            model_name='gradeoffering',
            constraint=models.UniqueConstraint(fields=('academic_cycle', 'shift', 'grade'), name='unique_grade_offering_per_cycle_shift'),
        ),
        migrations.AddConstraint(
            model_name='campus',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='unique_campus_code_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='campus',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('institution',), name='unique_main_campus_per_institution'),
        ),
    ]
