# Generated by Django 4.2.30 on 2026-08-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_academic_catalogue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academiccycle',
            options={'ordering': ['-starts_on', 'name']},
        ),
        migrations.AlterModelOptions(
            name='curriculumplan',
            options={'ordering': ['grade__level__sequence', 'grade__sequence', 'subject__name']},
        ),
        migrations.AlterModelOptions(
            name='teachingassignment',
            options={'ordering': ['section__name', 'subject__name', '-starts_on']},
        ),
        migrations.AlterUniqueTogether(
            name='academiccycle',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='curriculumplan',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='teachingassignment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='academiccycle',
            constraint=models.UniqueConstraint(fields=('institution', 'name'), name='unique_cycle_name_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='curriculumplan',
            constraint=models.UniqueConstraint(fields=('academic_cycle', 'grade', 'subject'), name='unique_subject_per_grade_and_cycle'),
        ),
        migrations.AddConstraint(
            model_name='teachingassignment',
            constraint=models.UniqueConstraint(fields=('academic_cycle', 'section', 'subject', 'teacher', 'starts_on'), name='unique_assignment_per_teacher_and_start'),
        ),
        migrations.AddConstraint(
            model_name='teachingassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('ends_on__isnull', True)), fields=('section', 'subject'), name='unique_open_assignment_per_section_subject'),
        ),
    ]
