# Generated by Django 5.2.17 on 2026-08-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_academic_cycle_foundation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='curriculumplan',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='curriculumplan',
            constraint=models.UniqueConstraint(fields=('academic_cycle', 'grade', 'subject'), name='unique_curriculum_plan_per_cycle_grade_subject'),
        ),
    ]
