# Generated by Django 5.2.17 on 2026-08-30 03:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_precreate_mineduc_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassScheduleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('number', models.PositiveSmallIntegerField(help_text='Order within the shift: 1, 2, 3, etc.')),
                ('name', models.CharField(help_text='Display name: "Bloque 1", "Recreo", etc.', max_length=100)),
                ('starts_on', models.TimeField(help_text='Start time of the block.')),
                ('ends_on', models.TimeField(help_text='End time of the block.')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_blocks', to='academics.shift')),
            ],
            options={
                'ordering': ['shift', 'number'],
                'constraints': [models.UniqueConstraint(fields=('shift', 'number'), name='unique_schedule_block_number_per_shift'), models.CheckConstraint(condition=models.Q(('starts_on__lt', models.F('ends_on'))), name='class_schedule_block_valid_times')],
            },
        ),
    ]
