# Generated by Django 5.2.17 on 2026-08-30 03:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_classscheduleblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('academic_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_sessions', to='academics.academiccycle')),
                ('schedule_block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_sessions', to='academics.classscheduleblock')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_sessions', to='academics.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_sessions', to='academics.subject')),
            ],
            options={
                'ordering': ['day_of_week', 'schedule_block__number'],
                'constraints': [models.UniqueConstraint(fields=('section', 'subject', 'day_of_week', 'schedule_block'), name='unique_class_session_registration')],
            },
        ),
    ]
