# Generated by Django 5.2.17 on 2026-08-30 04:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_classsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedulePublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('academic_cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_publication', to='academics.academiccycle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
