# Generated by Django 5.2.17 on 2026-08-30 04:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_classschedulepublication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30)),
                ('location', models.CharField(blank=True, help_text='Ubicacion dentro del campus, ej. "Edificio A, 2do nivel".', max_length=255)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='academics.campus')),
            ],
            options={
                'ordering': ['campus__name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('campus', 'code'), name='unique_classroom_code_per_campus')],
            },
        ),
    ]
