# Generated by Django 5.2.17 on 2026-08-30 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='classroom',
            field=models.ForeignKey(blank=True, help_text='Opcional: no toda sesion necesita un aula especifica (ej. educacion fisica).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_sessions', to='academics.classroom'),
        ),
    ]
