# Generated by Django 5.2.17 on 2026-09-06 06:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_class_session_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='starts_on',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Fecha desde la que la sesion esta vigente (RF-HOR-008).'),
        ),
    ]
