# Generated by Django 5.2.17 on 2026-09-06 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_class_session_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='default_classroom',
            field=models.ForeignKey(blank=True, help_text='Aula habitual de referencia para las clases de esta seccion (RF-AUL-002). No obliga a las sesiones individuales a usarla: cada ClassSession sigue llevando su propia aula, opcional (RF-AUL-003).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_for_sections', to='academics.classroom'),
        ),
    ]
