# Generated by Django 5.2.17 on 2026-09-17 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_classsession_starts_on'),
        ('academics', '0013_section_default_classroom'),
    ]

    operations = [
    ]
