# Generated by Django 5.2.17 on 2026-09-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_merge_0012_frozen_results_0014_merge_20260917_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='service_status',
            field=models.CharField(choices=[('available', 'Disponible'), ('unavailable', 'Temporalmente inhabilitada'), ('maintenance', 'En mantenimiento')], default='available', max_length=20),
        ),
    ]
