# Generated by Django 4.2.30 on 2026-07-29 02:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_on', models.DateField(default=django.utils.timezone.localdate)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('withdrawn', 'Withdrawn'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('academic_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', to='academics.academiccycle')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', to='academics.grade')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', to='academics.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', to='students.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='enrolment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('student', 'academic_cycle'), name='unique_active_enrolment_per_student_cycle'),
        ),
    ]
