# Generated by Django 5.2.17 on 2026-08-22 21:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolments', '0004_enrolment_duplicate_rules'),
        ('students', '0006_alter_guardian_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('movement_type', models.CharField(choices=[('section_change', 'Cambio de seccion'), ('transfer_in', 'Traslado de ingreso'), ('transfer_out', 'Traslado de egreso')], max_length=30)),
                ('effective_on', models.DateField(default=django.utils.timezone.localdate)),
                ('source_enrolment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_movements', to='enrolments.enrolment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='students.student')),
                ('target_enrolment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_movements', to='enrolments.enrolment')),
            ],
            options={
                'ordering': ['-effective_on', '-created_at', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('movement_type', 'section_change'), ('source_enrolment__isnull', False), ('target_enrolment__isnull', False)), models.Q(('movement_type', 'transfer_in'), ('source_enrolment__isnull', True), ('target_enrolment__isnull', False)), models.Q(('movement_type', 'transfer_out'), ('source_enrolment__isnull', False), ('target_enrolment__isnull', True)), _connector='OR'), name='student_movement_valid_enrolment_shape'), models.CheckConstraint(condition=models.Q(('source_enrolment__isnull', True), ('target_enrolment__isnull', True), models.Q(('source_enrolment', models.F('target_enrolment')), _negated=True), _connector='OR'), name='student_movement_distinct_enrolments')],
            },
        ),
    ]
