# Generated by Django 5.2.17 on 2026-08-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolments', '0005_studentmovement'),
        ('students', '0006_alter_guardian_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentmovement',
            name='student_movement_valid_enrolment_shape',
        ),
        migrations.AddField(
            model_name='studentmovement',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='studentmovement',
            name='movement_type',
            field=models.CharField(choices=[('section_change', 'Cambio de seccion'), ('transfer_in', 'Traslado de ingreso'), ('transfer_out', 'Traslado de egreso'), ('withdrawal', 'Retiro')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='studentmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type', 'section_change'), ('source_enrolment__isnull', False), ('target_enrolment__isnull', False)), models.Q(('movement_type', 'transfer_in'), ('source_enrolment__isnull', True), ('target_enrolment__isnull', False)), models.Q(('movement_type', 'transfer_out'), ('source_enrolment__isnull', False), ('target_enrolment__isnull', True)), models.Q(('movement_type', 'withdrawal'), ('source_enrolment__isnull', False), ('target_enrolment__isnull', True)), _connector='OR'), name='student_movement_valid_enrolment_shape'),
        ),
        migrations.AddConstraint(
            model_name='studentmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type', 'withdrawal'), _negated=True), models.Q(('reason', ''), _negated=True), _connector='OR'), name='student_withdrawal_requires_reason'),
        ),
    ]
