# Generated by Django 5.2.17 on 2026-09-01 22:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolments', '0006_student_withdrawal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMovementAnnulment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.TextField()),
                ('annulled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_movement_annulments', to=settings.AUTH_USER_MODEL)),
                ('movement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='annulment', to='enrolments.studentmovement')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='student_movement_annulment_requires_reason')],
            },
        ),
    ]
