# Generated by Django 5.2.16 on 2026-08-11 05:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTemplateVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sequence", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=150)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("certificate", "Certificado"),
                            ("report", "Reporte"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="documents.documenttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-sequence"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("template", "sequence"),
                        name="unique_document_template_version_sequence",
                    )
                ],
            },
        ),
    ]
