# Generated by Django 5.2.16 on 2026-08-19

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_documentrecord"),
        ("identity", "0007_seed_reporting_permissions"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="documenttemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(is_active=True),
                fields=("institution", "kind"),
                name="unique_active_document_template_per_kind_per_institution",
            ),
        ),
        migrations.CreateModel(
            name="DocumentDownloadToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("token_hash", models.CharField(max_length=128, unique=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=datetime.datetime(2026, 8, 19, 0, 0, tzinfo=datetime.timezone.utc)
                    ),
                ),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_download_tokens",
                        to="identity.useraccount",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="download_tokens",
                        to="documents.documentrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
