# Generated by Django 5.2.16 on 2026-08-19

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_academic_cycle_foundation"),
        ("documents", "0004_documentdownloadtoken_and_unique_active_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfficialFolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("year", models.PositiveSmallIntegerField()),
                ("sequence", models.PositiveIntegerField()),
                ("document_type", models.CharField(blank=True, max_length=50)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="official_folios",
                        to="academics.institution",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-sequence"],
            },
        ),
        migrations.AddConstraint(
            model_name="officialfolio",
            constraint=models.UniqueConstraint(
                fields=("institution", "year", "sequence"),
                name="unique_official_folio_per_institution_year_sequence",
            ),
        ),
    ]
