# Generated by Django 5.2.16 on 2026-08-20 04:38

import apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_officialfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentdownloadtoken',
            name='expires_at',
            field=models.DateTimeField(default=apps.documents.models.default_download_expiry),
        ),
    ]
