# Generated by Django 5.2.16 on 2026-09-03 02:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_documenttemplate_content_fields'),
        ('students', '0007_add_transferred_student_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentDeliveryReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('document_type', models.CharField(max_length=100)),
                ('folio', models.CharField(blank=True, max_length=100)),
                ('recipient_name', models.CharField(blank=True, max_length=150)),
                ('delivered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_delivery_receipts', to='students.guardian')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_delivery_receipts', to='students.student')),
            ],
            options={
                'ordering': ['-delivered_at', '-created_at'],
            },
        ),
    ]
