# Generated by Django 5.2 on 2026-09-05

import uuid

from django.db import migrations, models
import django.db.models.deletion


def backfill_document_version_groups(apps, schema_editor):
    DocumentRecord = apps.get_model("documents", "DocumentRecord")
    for record in DocumentRecord.objects.filter(version_group_id__isnull=True).iterator():
        record.version_group_id = uuid.uuid4()
        record.save(update_fields=["version_group_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0008_documentdeliveryreceipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentrecord",
            name="supersedes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="replacement_versions",
                to="documents.documentrecord",
            ),
        ),
        migrations.AddField(
            model_name="documentrecord",
            name="version_group_id",
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="documentrecord",
            name="version_number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(backfill_document_version_groups, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="documentrecord",
            name="version_group_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddConstraint(
            model_name="documentrecord",
            constraint=models.UniqueConstraint(
                fields=("version_group_id", "version_number"),
                name="unique_document_record_version_in_group",
            ),
        ),
    ]
