# Generated by Django 5.2 on 2026-09-05

from django.db import migrations


class Migration(migrations.Migration):
    """Join independent document feature migrations after stack integration."""

    dependencies = [
        ("documents", "0009_documentbatchrun"),
        ("documents", "0009_documentrecord_immutable_versions"),
    ]

    operations = []
