# Generated by Django 5.2 on 2026-09-05

from django.db import migrations


class Migration(migrations.Migration):
    """Join verification codes with the prior document migration graph."""

    dependencies = [
        ("documents", "0010_documentverificationcode"),
        ("documents", "0010_merge_document_versions_and_batch_runs"),
    ]

    operations = []
