# Generated by Django 5.2 on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0011_merge_document_verification_and_versions"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentverificationcode",
            name="folio",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
