# Generated by Django 4.2.30 on 2026-08-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='studentguardianrelation',
            constraint=models.UniqueConstraint(condition=models.Q(('ends_at__isnull', True)), fields=('student', 'guardian'), name='unique_active_student_guardian_relation'),
        ),
        migrations.AddConstraint(
            model_name='studentguardianrelation',
            constraint=models.UniqueConstraint(condition=models.Q(('ends_at__isnull', True), ('is_primary', True)), fields=('student',), name='unique_primary_guardian_per_student'),
        ),
    ]
