# Generated by Django 4.2.30 on 2026-08-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='photo_path',
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.FileField(blank=True, upload_to='student_photos/'),
        ),
    ]
