# Generated by Django 4.2.30 on 2026-08-07

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_remove_student_photo_path_student_photo"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="studentguardianrelation",
            constraint=models.UniqueConstraint(
                condition=Q(("ends_at__isnull", True), ("is_primary", True)),
                fields=("student",),
                name="students_one_current_primary_guardian",
            ),
        ),
    ]
