# Generated by Django 5.2.16 on 2026-08-19 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_merge_student_features'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guardian',
            options={'ordering': ['person__last_name', 'person__first_name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_code']},
        ),
        migrations.AlterModelOptions(
            name='studentguardianrelation',
            options={'ordering': ['-is_primary', '-starts_at', 'id']},
        ),
    ]
