# Generated by Django 5.2.16 on 2026-09-01 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_guardian_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('pre_enrolled', 'Pre-enrolled'), ('active', 'Active'), ('inactive', 'Inactive'), ('withdrawn', 'Withdrawn'), ('graduated', 'Graduated'), ('transferred', 'Transferred')], default='pre_enrolled', max_length=20),
        ),
    ]
