# Generated by Django 4.2.30 on 2026-08-04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("blocked", "Blocked"),
                    ("disabled", "Disabled"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
