# Generated by Django 4.2.30 on 2026-09-04

from django.db import migrations, models
import django.core.validators
import django.db.models.deletion


def link_existing_orphan_accounts(apps, schema_editor):
    """Preserve historical accounts by creating their institutional Person before tightening FK."""
    Person = apps.get_model("people", "Person")
    UserAccount = apps.get_model("identity", "UserAccount")

    for account in UserAccount.objects.filter(person__isnull=True).iterator():
        first_name = account.first_name.strip() or account.username[:150] or "Cuenta"
        last_name = account.last_name.strip() or "institucional"
        person = Person.objects.create(
            first_name=first_name,
            last_name=last_name,
            email=account.email,
        )
        account.person_id = person.pk
        account.save(update_fields=["person"])


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0008_seed_evaluation_configure_units_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="session_idle_timeout_minutes",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Minutos máximos de inactividad antes de cerrar la sesión.",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.RunPython(link_existing_orphan_accounts, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="useraccount",
            name="person",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_account",
                to="people.person",
            ),
        ),
    ]
